//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackoffSpec) DeepCopyInto(out *BackoffSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackoffSpec.
func (in *BackoffSpec) DeepCopy() *BackoffSpec {
	if in == nil {
		return nil
	}
	out := new(BackoffSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetrySpec) DeepCopyInto(out *RetrySpec) {
	*out = *in
	out.Backoff = in.Backoff
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetrySpec.
func (in *RetrySpec) DeepCopy() *RetrySpec {
	if in == nil {
		return nil
	}
	out := new(RetrySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryTimeoutConfig) DeepCopyInto(out *RetryTimeoutConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryTimeoutConfig.
func (in *RetryTimeoutConfig) DeepCopy() *RetryTimeoutConfig {
	if in == nil {
		return nil
	}
	out := new(RetryTimeoutConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetryTimeoutConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryTimeoutConfigList) DeepCopyInto(out *RetryTimeoutConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]RetryTimeoutConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryTimeoutConfigList.
func (in *RetryTimeoutConfigList) DeepCopy() *RetryTimeoutConfigList {
	if in == nil {
		return nil
	}
	out := new(RetryTimeoutConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *RetryTimeoutConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryTimeoutConfigSpec) DeepCopyInto(out *RetryTimeoutConfigSpec) {
	*out = *in
	out.TargetRef = in.TargetRef
	out.Default = in.Default
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryTimeoutConfigSpec.
func (in *RetryTimeoutConfigSpec) DeepCopy() *RetryTimeoutConfigSpec {
	if in == nil {
		return nil
	}
	out := new(RetryTimeoutConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *RetryTimeoutDefaultSpec) DeepCopyInto(out *RetryTimeoutDefaultSpec) {
	*out = *in
	out.Retry = in.Retry
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new RetryTimeoutDefaultSpec.
func (in *RetryTimeoutDefaultSpec) DeepCopy() *RetryTimeoutDefaultSpec {
	if in == nil {
		return nil
	}
	out := new(RetryTimeoutDefaultSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TargetRefSpec) DeepCopyInto(out *TargetRefSpec) {
	*out = *in
	out.ObjectReference = in.ObjectReference
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TargetRefSpec.
func (in *TargetRefSpec) DeepCopy() *TargetRefSpec {
	if in == nil {
		return nil
	}
	out := new(TargetRefSpec)
	in.DeepCopyInto(out)
	return out
}
