version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/service-mesh"
  - package-ecosystem: "gomod"
    directory: "/"
    schedule:
      interval: daily
    reviewers:
      - "nginxinc/service-mesh"
