//go:build !ignore_autogenerated
// +build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha2

import (
	"k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ExportersSpec) DeepCopyInto(out *ExportersSpec) {
	*out = *in
	in.Otlp.DeepCopyInto(&out.Otlp)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ExportersSpec.
func (in *ExportersSpec) DeepCopy() *ExportersSpec {
	if in == nil {
		return nil
	}
	out := new(ExportersSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfig) DeepCopyInto(out *MeshConfig) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfig.
func (in *MeshConfig) DeepCopy() *MeshConfig {
	if in == nil {
		return nil
	}
	out := new(MeshConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshConfig) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigClass) DeepCopyInto(out *MeshConfigClass) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigClass.
func (in *MeshConfigClass) DeepCopy() *MeshConfigClass {
	if in == nil {
		return nil
	}
	out := new(MeshConfigClass)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshConfigClass) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigClassList) DeepCopyInto(out *MeshConfigClassList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeshConfigClass, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigClassList.
func (in *MeshConfigClassList) DeepCopy() *MeshConfigClassList {
	if in == nil {
		return nil
	}
	out := new(MeshConfigClassList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshConfigClassList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigClassSpec) DeepCopyInto(out *MeshConfigClassSpec) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigClassSpec.
func (in *MeshConfigClassSpec) DeepCopy() *MeshConfigClassSpec {
	if in == nil {
		return nil
	}
	out := new(MeshConfigClassSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigClassStatus) DeepCopyInto(out *MeshConfigClassStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigClassStatus.
func (in *MeshConfigClassStatus) DeepCopy() *MeshConfigClassStatus {
	if in == nil {
		return nil
	}
	out := new(MeshConfigClassStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigList) DeepCopyInto(out *MeshConfigList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MeshConfig, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigList.
func (in *MeshConfigList) DeepCopy() *MeshConfigList {
	if in == nil {
		return nil
	}
	out := new(MeshConfigList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MeshConfigList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigSpec) DeepCopyInto(out *MeshConfigSpec) {
	*out = *in
	if in.Mtls != nil {
		in, out := &in.Mtls, &out.Mtls
		*out = new(MtlsSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.AccessControlMode != nil {
		in, out := &in.AccessControlMode, &out.AccessControlMode
		*out = new(string)
		**out = **in
	}
	if in.ClientMaxBodySize != nil {
		in, out := &in.ClientMaxBodySize, &out.ClientMaxBodySize
		*out = new(string)
		**out = **in
	}
	if in.NGINXErrorLogLevel != nil {
		in, out := &in.NGINXErrorLogLevel, &out.NGINXErrorLogLevel
		*out = new(string)
		**out = **in
	}
	if in.NGINXLBMethod != nil {
		in, out := &in.NGINXLBMethod, &out.NGINXLBMethod
		*out = new(string)
		**out = **in
	}
	if in.NGINXLogFormat != nil {
		in, out := &in.NGINXLogFormat, &out.NGINXLogFormat
		*out = new(string)
		**out = **in
	}
	if in.PrometheusAddress != nil {
		in, out := &in.PrometheusAddress, &out.PrometheusAddress
		*out = new(string)
		**out = **in
	}
	if in.Telemetry != nil {
		in, out := &in.Telemetry, &out.Telemetry
		*out = new(TelemetrySpec)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigSpec.
func (in *MeshConfigSpec) DeepCopy() *MeshConfigSpec {
	if in == nil {
		return nil
	}
	out := new(MeshConfigSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MeshConfigStatus) DeepCopyInto(out *MeshConfigStatus) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MeshConfigStatus.
func (in *MeshConfigStatus) DeepCopy() *MeshConfigStatus {
	if in == nil {
		return nil
	}
	out := new(MeshConfigStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MtlsSpec) DeepCopyInto(out *MtlsSpec) {
	*out = *in
	if in.Mode != nil {
		in, out := &in.Mode, &out.Mode
		*out = new(string)
		**out = **in
	}
	if in.CaKeyType != nil {
		in, out := &in.CaKeyType, &out.CaKeyType
		*out = new(string)
		**out = **in
	}
	if in.CaTTL != nil {
		in, out := &in.CaTTL, &out.CaTTL
		*out = new(string)
		**out = **in
	}
	if in.SvidTTL != nil {
		in, out := &in.SvidTTL, &out.SvidTTL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MtlsSpec.
func (in *MtlsSpec) DeepCopy() *MtlsSpec {
	if in == nil {
		return nil
	}
	out := new(MtlsSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OtlpSpec) DeepCopyInto(out *OtlpSpec) {
	*out = *in
	if in.Host != nil {
		in, out := &in.Host, &out.Host
		*out = new(string)
		**out = **in
	}
	if in.Port != nil {
		in, out := &in.Port, &out.Port
		*out = new(int32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OtlpSpec.
func (in *OtlpSpec) DeepCopy() *OtlpSpec {
	if in == nil {
		return nil
	}
	out := new(OtlpSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *TelemetrySpec) DeepCopyInto(out *TelemetrySpec) {
	*out = *in
	if in.Exporters != nil {
		in, out := &in.Exporters, &out.Exporters
		*out = new(ExportersSpec)
		(*in).DeepCopyInto(*out)
	}
	if in.SamplerRatio != nil {
		in, out := &in.SamplerRatio, &out.SamplerRatio
		*out = new(float32)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new TelemetrySpec.
func (in *TelemetrySpec) DeepCopy() *TelemetrySpec {
	if in == nil {
		return nil
	}
	out := new(TelemetrySpec)
	in.DeepCopyInto(out)
	return out
}
