linters:
  enable-all: true
  disable:
    - testpackage
    - cyclop
    - exhaustivestruct # [deprecated]
    - exhaustruct
    - forbidigo # (forbids use of fmt.Print* in a command line app)
    - funlen
    - gci # (errors not fixable by latest gci tool)
    - gochecknoglobals
    - gocognit
    - godox
    - golint # [deprecated]
    - gomoddirectives
    - interfacer # [deprecated]
    - ireturn
    - maintidx
    - maligned # [deprecated]
    - nestif
    - scopelint # [deprecated]
    - tagliatelle
    - wrapcheck
    - wsl
run:
  timeout: 10m
  skip-files:
    - ".*\\.gen\\.go"
    - "internal/nginx-meshctl/support/printers.go"
linters-settings:
  gocyclo:
    # minimal code complexity to report, 30 by default (but we recommend 10-20)
    min-complexity: 30
  gci:
    # put imports beginning with prefix after 3rd-party packages;
    # only supports one prefix
    # if not set, use goimports.local-prefixes
    local-prefixes: github.com/nginxinc/nginx-service-mesh
  govet:
    enable:
      - fieldalignment
    check-shadowing: true
  errcheck:
     ignore: ^Close.*,fmt:.*,github.com/spf13/viper:.*
  lll:
    line-length: 140
  nakedret:
    max-func-lines: 0
  gocritic:
    enabled-tags:
      - style
    disabled-checks:
      - wrapperFunc
      - dupImport # https://github.com/go-critic/go-critic/issues/845
issues:
  exclude-use-default: false
  exclude-rules:
    - text: "G104" # gosec G104 is caught by errcheck
      linters:
        - gosec
    - text: "G107" # Potential HTTP request made with variable url.
      linters:
        - gosec
    # allow passing file perms without variables
    - text: "mnd: Magic number: 0o[0-7][0-7][0-7], in <argument> detected"
      linters:
        - gomnd
    # ignore false positives from os package
    - text: "O_(APPEND|CREATE|WRONLY) contains underscore. You should use mixedCap or MixedCap."
      linters:
        - nosnakecase
    # directly contradicts other linters
    - text: "unnamedResult: consider giving a name to these results"
      linters:
        - gocritic
