env:
  - CGO_ENABLED=0

builds:
  - id: nginx-meshctl
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -extldflags "-fno-PIC -static" -X main.version={{.Version}} -X main.pkgName=nginx-meshctl
    main: ./cmd/nginx-meshctl/
    binary: nginx-meshctl

changelog:
  skip: true

checksum:
  name_template: checksums.txt

sboms:
  - artifacts: archive

release:
  ids: [nginx-meshctl]
  header: |
    NGINX Service Mesh Release {{.Version}}

    [Release Notes](https://docs.nginx.com/nginx-service-mesh/releases/release-notes-{{.Version}}/)

archives:
  - id: nginx-meshctl
    builds: [nginx-meshctl]
    name_template: nginx-meshctl_{{ .Version }}_{{ .Os }}_{{ .Arch }}
    format_overrides:
      - goos: windows
        format: zip

blobs:
  - provider: azblob
    bucket: '{{.Env.AZURE_BUCKET_NAME}}'
    extra_files:
      - glob: ./dist/**.sbom
