apiVersion: 1
datasources:
- name: prometheus
  type: prometheus
  access: proxy
  orgId: 1
  url: http://{{ include "prometheus.address" . }}
  isDefault: true
  jsonData:
    timeInterval: "5s"
version: 1
editable: true
