apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: nginx-ingress-permissions
allowHostDirVolumePlugin: false
allowHostIPC: false
allowHostNetwork: false
allowHostPID: false
allowHostPorts: true
allowPrivilegeEscalation: true
allowPrivilegedContainer: false
allowedCapabilities:
- NET_BIND_SERVICE
seLinuxContext:
  type: MustRunAs
runAsUser:
  type: MustRunAs
  uid: 101
fsGroup:
  type: MustRunAs
readOnlyRootFilesystem: false
requiredDropCapabilities:
- KILL
- MKNOD
- SETUID
- SETGID
volumes:
- csi
- projected
