{{- if .Values.tracing }} {{ if (and (not .Values.tracing.disable) (eq .Values.tracing.backend "jaeger") (eq .Values.tracing.address "")) }}
---
apiVersion: v1
kind: Service
metadata:
  name: jaeger
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  selector:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: nginx-service-mesh
  type: ClusterIP
  ports:
  - name: frontend
    port: 16686
    targetPort: 16686
  - name: collector
    port: 6831
    targetPort: 6831
    protocol: UDP
  - name: collector-http
    port: 14268
    protocol: TCP
    targetPort: 14268
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jaeger
  labels:
    app.kubernetes.io/name: jaeger
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: jaeger
      app.kubernetes.io/part-of: nginx-service-mesh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jaeger
        app.kubernetes.io/part-of: nginx-service-mesh
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '16686'
    spec:
      imagePullSecrets:
      - name: {{ include "registry-key-name" . }}
      containers:
      - name: jaeger
        image: {{ include "jaeger.image-server" . }}/all-in-one:1.31.0
        imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
        ports:
        - containerPort: 16686
        - containerPort: 6831
          protocol: UDP
{{- end }}{{- end }}
