{{- if eq .Values.prometheusAddress "" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
imagePullSecrets:
- name: {{ include "registry-key-name" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: prometheus.metrics.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
rules:
- apiGroups:
  - ''
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- nonResourceURLs:
  - "/metrics"
  verbs:
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: prometheus.metrics.builtin.nsm.nginx
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: prometheus.metrics.builtin.nsm.nginx
subjects:
- kind: ServiceAccount
  name: prometheus
  namespace: {{ .Release.Namespace }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-configuration
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
binaryData:
  prometheus.yaml: {{ .Files.Get "configs/prometheus-config.yaml" | b64enc }}
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  selector:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: nginx-service-mesh
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9090
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: prometheus
      app.kubernetes.io/part-of: nginx-service-mesh
  template:
    metadata:
      labels:
        app.kubernetes.io/name: prometheus
        app.kubernetes.io/part-of: nginx-service-mesh
    spec:
      serviceAccountName: prometheus
      containers:
      - name: prometheus
        image: {{ include "prometheus.image-server" . }}/prometheus:v2.33.1
        imagePullPolicy: {{ .Values.registry.imagePullPolicy }}
        args:
        - "--config.file=/etc/prometheus/prometheus.yaml"
        - "--storage.tsdb.path=/prometheus/"
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config-volume
          mountPath: "/etc/prometheus"
        - name: prometheus-storage-volume
          mountPath: "/prometheus/"
      volumes:
      - name: prometheus-config-volume
        configMap:
          name: prometheus-configuration
      - name: prometheus-storage-volume
        emptyDir: {}
{{- end }}
