// Package mesh provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.12.4 DO NOT EDIT.
package mesh

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
)

// Defines values for MeshConfigAccessControlMode.
const (
	MeshConfigAccessControlModeAllow MeshConfigAccessControlMode = "allow"
	MeshConfigAccessControlModeDeny  MeshConfigAccessControlMode = "deny"
)

// Defines values for MeshConfigEnvironment.
const (
	Kubernetes MeshConfigEnvironment = "kubernetes"
	Openshift  MeshConfigEnvironment = "openshift"
)

// Defines values for MeshConfigLoadBalancingMethod.
const (
	MeshConfigLoadBalancingMethodLeastConn                  MeshConfigLoadBalancingMethod = "least_conn"
	MeshConfigLoadBalancingMethodLeastTime                  MeshConfigLoadBalancingMethod = "least_time"
	MeshConfigLoadBalancingMethodLeastTimeLastByte          MeshConfigLoadBalancingMethod = "least_time last_byte"
	MeshConfigLoadBalancingMethodLeastTimeLastByteInflight  MeshConfigLoadBalancingMethod = "least_time last_byte inflight"
	MeshConfigLoadBalancingMethodRandom                     MeshConfigLoadBalancingMethod = "random"
	MeshConfigLoadBalancingMethodRandomTwo                  MeshConfigLoadBalancingMethod = "random two"
	MeshConfigLoadBalancingMethodRandomTwoLeastConn         MeshConfigLoadBalancingMethod = "random two least_conn"
	MeshConfigLoadBalancingMethodRandomTwoLeastTime         MeshConfigLoadBalancingMethod = "random two least_time"
	MeshConfigLoadBalancingMethodRandomTwoLeastTimeLastByte MeshConfigLoadBalancingMethod = "random two least_time=last_byte"
	MeshConfigLoadBalancingMethodRoundRobin                 MeshConfigLoadBalancingMethod = "round_robin"
)

// Defines values for MeshConfigNginxErrorLogLevel.
const (
	MeshConfigNginxErrorLogLevelAlert  MeshConfigNginxErrorLogLevel = "alert"
	MeshConfigNginxErrorLogLevelCrit   MeshConfigNginxErrorLogLevel = "crit"
	MeshConfigNginxErrorLogLevelDebug  MeshConfigNginxErrorLogLevel = "debug"
	MeshConfigNginxErrorLogLevelEmerg  MeshConfigNginxErrorLogLevel = "emerg"
	MeshConfigNginxErrorLogLevelError  MeshConfigNginxErrorLogLevel = "error"
	MeshConfigNginxErrorLogLevelInfo   MeshConfigNginxErrorLogLevel = "info"
	MeshConfigNginxErrorLogLevelNotice MeshConfigNginxErrorLogLevel = "notice"
	MeshConfigNginxErrorLogLevelWarn   MeshConfigNginxErrorLogLevel = "warn"
)

// Defines values for MeshConfigNginxLogFormat.
const (
	MeshConfigNginxLogFormatDefault MeshConfigNginxLogFormat = "default"
	MeshConfigNginxLogFormatJson    MeshConfigNginxLogFormat = "json"
)

// Defines values for MtlsConfigCaKeyType.
const (
	EcP256  MtlsConfigCaKeyType = "ec-p256"
	EcP384  MtlsConfigCaKeyType = "ec-p384"
	Rsa2048 MtlsConfigCaKeyType = "rsa-2048"
	Rsa4096 MtlsConfigCaKeyType = "rsa-4096"
)

// Defines values for MtlsConfigMode.
const (
	Off        MtlsConfigMode = "off"
	Permissive MtlsConfigMode = "permissive"
	Strict     MtlsConfigMode = "strict"
)

// Defines values for PatchConfigFieldAccessControlMode.
const (
	PatchConfigFieldAccessControlModeAllow PatchConfigFieldAccessControlMode = "allow"
	PatchConfigFieldAccessControlModeDeny  PatchConfigFieldAccessControlMode = "deny"
)

// Defines values for PatchConfigFieldLoadBalancingMethod.
const (
	PatchConfigFieldLoadBalancingMethodLeastConn                  PatchConfigFieldLoadBalancingMethod = "least_conn"
	PatchConfigFieldLoadBalancingMethodLeastTime                  PatchConfigFieldLoadBalancingMethod = "least_time"
	PatchConfigFieldLoadBalancingMethodLeastTimeLastByte          PatchConfigFieldLoadBalancingMethod = "least_time last_byte"
	PatchConfigFieldLoadBalancingMethodLeastTimeLastByteInflight  PatchConfigFieldLoadBalancingMethod = "least_time last_byte inflight"
	PatchConfigFieldLoadBalancingMethodRandom                     PatchConfigFieldLoadBalancingMethod = "random"
	PatchConfigFieldLoadBalancingMethodRandomTwo                  PatchConfigFieldLoadBalancingMethod = "random two"
	PatchConfigFieldLoadBalancingMethodRandomTwoLeastConn         PatchConfigFieldLoadBalancingMethod = "random two least_conn"
	PatchConfigFieldLoadBalancingMethodRandomTwoLeastTime         PatchConfigFieldLoadBalancingMethod = "random two least_time"
	PatchConfigFieldLoadBalancingMethodRandomTwoLeastTimeLastByte PatchConfigFieldLoadBalancingMethod = "random two least_time=last_byte"
	PatchConfigFieldLoadBalancingMethodRoundRobin                 PatchConfigFieldLoadBalancingMethod = "round_robin"
)

// Defines values for PatchConfigFieldNginxErrorLogLevel.
const (
	PatchConfigFieldNginxErrorLogLevelAlert  PatchConfigFieldNginxErrorLogLevel = "alert"
	PatchConfigFieldNginxErrorLogLevelCrit   PatchConfigFieldNginxErrorLogLevel = "crit"
	PatchConfigFieldNginxErrorLogLevelDebug  PatchConfigFieldNginxErrorLogLevel = "debug"
	PatchConfigFieldNginxErrorLogLevelEmerg  PatchConfigFieldNginxErrorLogLevel = "emerg"
	PatchConfigFieldNginxErrorLogLevelError  PatchConfigFieldNginxErrorLogLevel = "error"
	PatchConfigFieldNginxErrorLogLevelInfo   PatchConfigFieldNginxErrorLogLevel = "info"
	PatchConfigFieldNginxErrorLogLevelNotice PatchConfigFieldNginxErrorLogLevel = "notice"
	PatchConfigFieldNginxErrorLogLevelWarn   PatchConfigFieldNginxErrorLogLevel = "warn"
)

// Defines values for PatchConfigFieldNginxLogFormat.
const (
	PatchConfigFieldNginxLogFormatDefault PatchConfigFieldNginxLogFormat = "default"
	PatchConfigFieldNginxLogFormatJson    PatchConfigFieldNginxLogFormat = "json"
)

// Defines values for PatchConfigOp.
const (
	Add     PatchConfigOp = "add"
	Remove  PatchConfigOp = "remove"
	Replace PatchConfigOp = "replace"
)

// APIConfig The configuration of the NGINX Service Mesh API.
type APIConfig struct {
	// Address The Kubernetes DNS name of the NGINX Service Mesh API.
	Address string `json:"address"`

	// ContainerPort The container port of the NGINX Service Mesh API.
	ContainerPort int `json:"containerPort"`

	// Port The port of the NGINX Service Mesh API.
	Port int `json:"port"`
}

// ErrorDetail defines model for ErrorDetail.
type ErrorDetail struct {
	// Description A detailed error message returned by the server.
	//
	// These messages contain the following information, where applicable:
	//
	// - What happened.
	// - Why it happened.
	// - What the consequences are (if any).
	// - Recommended action to take to resolve the issue.
	Description string `json:"description"`
}

// ErrorModel defines model for ErrorModel.
type ErrorModel struct {
	// Code A numeric error code that can be used to identify errors for support purposes.
	Code    int            `json:"code"`
	Details *[]ErrorDetail `json:"details,omitempty"`

	// Message A human-readable message, in English, that describes the error.
	Message string `json:"message"`
}

// ExportersConfig The configuration of exporters to send telemetry data to.
type ExportersConfig struct {
	// Otlp The configuration for an OTLP gRPC exporter.
	Otlp *OtlpExporterConfig `json:"otlp,omitempty"`
}

// Image A container image, comprised of an image name and image tag.
type Image struct {
	// Image The tag of the image.
	Image string `json:"image"`

	// Name The name of the image.
	Name string `json:"name"`
}

// MeshConfig Holds combined configuration required to run the NGINX Service Mesh control plane
// and the data plane.
type MeshConfig struct {
	// AccessControlMode The access control mode of NGINX Service Mesh.
	AccessControlMode MeshConfigAccessControlMode `json:"accessControlMode"`

	// Api The configuration of the NGINX Service Mesh API.
	Api APIConfig `json:"api"`

	// AutoInjectorPort The port that the automatic injection webhook binds to.
	AutoInjectorPort int `json:"autoInjectorPort"`

	// ClientMaxBodySize The maximum allowed size of the client request body.
	ClientMaxBodySize string `json:"clientMaxBodySize"`

	// Environment The environment that the NGINX Service Mesh control plane is installed in.
	Environment MeshConfigEnvironment `json:"environment"`

	// IsUDPEnabled Enable UDP traffic proxying.
	IsUDPEnabled bool `json:"isUDPEnabled"`

	// LoadBalancingMethod The global load balancing method for Services in NGINX Service Mesh. This value can be overridden on a per-Service basis with a Service annotation.
	LoadBalancingMethod MeshConfigLoadBalancingMethod `json:"loadBalancingMethod"`

	// Mtls The configuration for mTLS.
	Mtls MtlsConfig `json:"mtls"`

	// Namespace The namespace where the NGINX Service Mesh control plane is installed.
	Namespace string `json:"namespace"`

	// NginxErrorLogLevel The error log level of the NGINX Service Mesh sidecar proxies.
	NginxErrorLogLevel MeshConfigNginxErrorLogLevel `json:"nginxErrorLogLevel"`

	// NginxLogFormat The log format of the NGINX Service Mesh sidecar proxies.
	NginxLogFormat MeshConfigNginxLogFormat `json:"nginxLogFormat"`

	// PrometheusAddress The address of the Prometheus server deployment.
	PrometheusAddress string `json:"prometheusAddress"`

	// Proxy The configuration of the NGINX Service Mesh sidecar proxies.
	Proxy ProxyConfig `json:"proxy"`

	// RegistryKeyName The name of the registry key that is used to pull the NGINX Service Mesh docker images.
	RegistryKeyName string `json:"registryKeyName"`

	// SidecarImage A container image, comprised of an image name and image tag.
	SidecarImage Image `json:"sidecarImage"`

	// SidecarInitImage A container image, comprised of an image name and image tag.
	SidecarInitImage Image `json:"sidecarInitImage"`

	// Telemetry The configuration for telemetry.
	Telemetry TelemetryConfig `json:"telemetry"`

	// TrustDomain The trust domain of the NGINX Service Mesh.
	TrustDomain string `json:"trustDomain"`
}

// MeshConfigAccessControlMode The access control mode of NGINX Service Mesh.
type MeshConfigAccessControlMode string

// MeshConfigEnvironment The environment that the NGINX Service Mesh control plane is installed in.
type MeshConfigEnvironment string

// MeshConfigLoadBalancingMethod The global load balancing method for Services in NGINX Service Mesh. This value can be overridden on a per-Service basis with a Service annotation.
type MeshConfigLoadBalancingMethod string

// MeshConfigNginxErrorLogLevel The error log level of the NGINX Service Mesh sidecar proxies.
type MeshConfigNginxErrorLogLevel string

// MeshConfigNginxLogFormat The log format of the NGINX Service Mesh sidecar proxies.
type MeshConfigNginxLogFormat string

// MtlsConfig The configuration for mTLS.
type MtlsConfig struct {
	// CaKeyType The key type used for the SPIRE Server CA.
	CaKeyType *MtlsConfigCaKeyType `json:"caKeyType,omitempty"`

	// CaTTL The CA/signing key TTL in hours(h). Min value 24h. Max value 999999h.
	CaTTL *string `json:"caTTL,omitempty"`

	// Mode The mTLS mode of NGINX Service Mesh.
	Mode *MtlsConfigMode `json:"mode,omitempty"`

	// SvidTTL The TTL of certificates issued to workloads in hours(h) or minutes(m). Max value is 999999.
	SvidTTL *string `json:"svidTTL,omitempty"`
}

// MtlsConfigCaKeyType The key type used for the SPIRE Server CA.
type MtlsConfigCaKeyType string

// MtlsConfigMode The mTLS mode of NGINX Service Mesh.
type MtlsConfigMode string

// OtlpExporterConfig The configuration for an OTLP gRPC exporter.
type OtlpExporterConfig struct {
	// Host The host of the OpenTelemetry gRPC exporter to connect to.
	Host string `json:"host"`

	// Port The port of the OpenTelemetry gRPC exporter to connect to.
	Port int `json:"port"`
}

// PatchConfig The configuration object that holds the updates to be made to the NGINX Service Mesh configuration.
type PatchConfig struct {
	Field struct {
		// AccessControlMode The access control mode of NGINX Service Mesh.
		AccessControlMode *PatchConfigFieldAccessControlMode `json:"accessControlMode,omitempty"`

		// ClientMaxBodySize The maximum allowed size of the client request body.
		ClientMaxBodySize *string `json:"clientMaxBodySize,omitempty"`

		// LoadBalancingMethod The global load balancing method for Services in NGINX Service Mesh. This value can be overridden on a per-Service basis with a Service annotation.
		LoadBalancingMethod *PatchConfigFieldLoadBalancingMethod `json:"loadBalancingMethod,omitempty"`

		// Mtls The configuration for mTLS.
		Mtls *MtlsConfig `json:"mtls,omitempty"`

		// NginxErrorLogLevel The error log level of the NGINX Service Mesh sidecar proxies.
		NginxErrorLogLevel *PatchConfigFieldNginxErrorLogLevel `json:"nginxErrorLogLevel,omitempty"`

		// NginxLogFormat The log format of the NGINX Service Mesh sidecar proxies.
		NginxLogFormat *PatchConfigFieldNginxLogFormat `json:"nginxLogFormat,omitempty"`

		// PrometheusAddress The address of the Prometheus server. Must be reachable from the Kubernetes cluster that NGINX Service Mesh is installed in.
		PrometheusAddress *string `json:"prometheusAddress,omitempty"`

		// Telemetry The configuration for telemetry.
		Telemetry *TelemetryConfig `json:"telemetry,omitempty"`
	} `json:"field"`

	// Op The type of operation to be performed on the NGINX Service Mesh configuration. Values in the NGINX Service Mesh configuration can be added, removed, or replaced.
	Op PatchConfigOp `json:"op"`
}

// PatchConfigFieldAccessControlMode The access control mode of NGINX Service Mesh.
type PatchConfigFieldAccessControlMode string

// PatchConfigFieldLoadBalancingMethod The global load balancing method for Services in NGINX Service Mesh. This value can be overridden on a per-Service basis with a Service annotation.
type PatchConfigFieldLoadBalancingMethod string

// PatchConfigFieldNginxErrorLogLevel The error log level of the NGINX Service Mesh sidecar proxies.
type PatchConfigFieldNginxErrorLogLevel string

// PatchConfigFieldNginxLogFormat The log format of the NGINX Service Mesh sidecar proxies.
type PatchConfigFieldNginxLogFormat string

// PatchConfigOp The type of operation to be performed on the NGINX Service Mesh configuration. Values in the NGINX Service Mesh configuration can be added, removed, or replaced.
type PatchConfigOp string

// PortsConfig The ports that the NGINX Service Mesh sidecar proxies listen on.
type PortsConfig struct {
	// Incoming The incoming HTTP port.
	Incoming int `json:"incoming"`

	// IncomingGrpc The incoming gRPC port.
	IncomingGrpc int `json:"incomingGrpc"`

	// IncomingGrpcPermissive The incoming gRPC port when the mTLS mode of the sidecar proxy is set to permissive.
	IncomingGrpcPermissive int `json:"incomingGrpcPermissive"`

	// IncomingNotInKeyval The incoming port that handles requests from Services not in the NGINX Service Mesh.
	IncomingNotInKeyval int `json:"incomingNotInKeyval"`

	// IncomingPermissive The incoming HTTP port when the mTLS mode of the sidecar proxy is set to permissive.
	IncomingPermissive int `json:"incomingPermissive"`

	// IncomingRedirect The incoming redirect port. This port redirects requests to another port on the sidecar proxy based on the protocol of the request.
	IncomingRedirect int `json:"incomingRedirect"`

	// IncomingTcp The incoming TCP port.
	IncomingTcp int `json:"incomingTcp"`

	// IncomingTcpDeny The incoming TCP deny port. This port denies TCP traffic if it is not a part of NGINX Service Mesh or if the access to the sidecar is not allowed.
	IncomingTcpDeny int `json:"incomingTcpDeny"`

	// IncomingTcpPermissive The incoming TCP port when the mTLS mode of the sidecar proxy is set to perissive.
	IncomingTcpPermissive int `json:"incomingTcpPermissive"`

	// IncomingUdp The incoming UDP port.
	IncomingUdp int `json:"incomingUdp"`

	// Metrics The Prometheus metrics port.
	Metrics int `json:"metrics"`

	// Outgoing The outgoing HTTP port.
	Outgoing int `json:"outgoing"`

	// OutgoingDefaultEgress The outgoing traffic port for egress traffic when the NGINX Plus Ingress Controller is deployed as an egress controller.
	OutgoingDefaultEgress int `json:"outgoingDefaultEgress"`

	// OutgoingGrpc The outgoing gRPC port.
	OutgoingGrpc int `json:"outgoingGrpc"`

	// OutgoingNotInKeyval The outgoing port for destinations that are not a part of NGINX Service Mesh.
	OutgoingNotInKeyval int `json:"outgoingNotInKeyval"`

	// OutgoingRedirect The outgoing redirect port. This port redirects requests to another port on the sidecar proxy based on the protocol of the request.
	OutgoingRedirect int `json:"outgoingRedirect"`

	// OutgoingTcp The outgoing TCP port.
	OutgoingTcp int `json:"outgoingTcp"`

	// OutgoingUdp The outgoing UDP port.
	OutgoingUdp int `json:"outgoingUdp"`

	// PlusApi The port for the NGINX Plus API. This API is not accessible outside of the NGINX Service Mesh sidecar container.
	PlusApi int `json:"plusApi"`

	// RedirectHealthPort This port redirects HTTP health probes to the application container.
	RedirectHealthPort int `json:"redirectHealthPort"`

	// RedirectHealthPortHTTPS This port redirects HTTPS health probes to the application container.
	RedirectHealthPortHTTPS int `json:"redirectHealthPortHTTPS"`
}

// ProxyConfig The configuration of the NGINX Service Mesh sidecar proxies.
type ProxyConfig struct {
	// Ports The ports that the NGINX Service Mesh sidecar proxies listen on.
	Ports PortsConfig `json:"ports"`

	// Transparent Whether or not the NGINX Service Mesh sidecar proxies are running in transparent mode. Transparent mode means that the sidecar proxies are passing the traffic through to the destination without applying any rules to the traffic.
	Transparent bool `json:"transparent"`
}

// TelemetryConfig The configuration for telemetry.
type TelemetryConfig struct {
	// Exporters The configuration of exporters to send telemetry data to.
	Exporters *ExportersConfig `json:"exporters,omitempty"`

	// SamplerRatio The percentage of traces that are processed and exported to the telemetry backend.
	SamplerRatio *float32 `json:"samplerRatio,omitempty"`
}

// BadRequest defines model for BadRequest.
type BadRequest = ErrorModel

// Forbidden defines model for Forbidden.
type Forbidden = ErrorModel

// InternalServerError defines model for InternalServerError.
type InternalServerError = ErrorModel

// Unauthorized defines model for Unauthorized.
type Unauthorized = ErrorModel

// PatchConfigJSONBody defines parameters for PatchConfig.
type PatchConfigJSONBody struct {
	union json.RawMessage
}

// PatchConfigJSONBody1 defines parameters for PatchConfig.
type PatchConfigJSONBody1 = []PatchConfig

// PatchConfigJSONRequestBody defines body for PatchConfig for application/json ContentType.
type PatchConfigJSONRequestBody PatchConfigJSONBody

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// GetConfig request
	GetConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PatchConfig request with any body
	PatchConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PatchConfig(ctx context.Context, body PatchConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) GetConfig(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetConfigRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchConfigWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchConfigRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PatchConfig(ctx context.Context, body PatchConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPatchConfigRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewGetConfigRequest generates requests for GetConfig
func NewGetConfigRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPatchConfigRequest calls the generic PatchConfig builder with application/json body
func NewPatchConfigRequest(server string, body PatchConfigJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPatchConfigRequestWithBody(server, "application/json", bodyReader)
}

// NewPatchConfigRequestWithBody generates requests for PatchConfig with any type of body
func NewPatchConfigRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/config")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PATCH", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// GetConfig request
	GetConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetConfigResponse, error)

	// PatchConfig request with any body
	PatchConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchConfigResponse, error)

	PatchConfigWithResponse(ctx context.Context, body PatchConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchConfigResponse, error)
}

type GetConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MeshConfig
	JSON401      *ErrorModel
	JSON403      *ErrorModel
	JSON500      *ErrorModel
}

// Status returns HTTPResponse.Status
func (r GetConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PatchConfigResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *MeshConfig
	JSON400      *ErrorModel
	JSON401      *ErrorModel
	JSON403      *ErrorModel
}

// Status returns HTTPResponse.Status
func (r PatchConfigResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PatchConfigResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// GetConfigWithResponse request returning *GetConfigResponse
func (c *ClientWithResponses) GetConfigWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetConfigResponse, error) {
	rsp, err := c.GetConfig(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetConfigResponse(rsp)
}

// PatchConfigWithBodyWithResponse request with arbitrary body returning *PatchConfigResponse
func (c *ClientWithResponses) PatchConfigWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PatchConfigResponse, error) {
	rsp, err := c.PatchConfigWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchConfigResponse(rsp)
}

func (c *ClientWithResponses) PatchConfigWithResponse(ctx context.Context, body PatchConfigJSONRequestBody, reqEditors ...RequestEditorFn) (*PatchConfigResponse, error) {
	rsp, err := c.PatchConfig(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePatchConfigResponse(rsp)
}

// ParseGetConfigResponse parses an HTTP response from a GetConfigWithResponse call
func ParseGetConfigResponse(rsp *http.Response) (*GetConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MeshConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON500 = &dest

	}

	return response, nil
}

// ParsePatchConfigResponse parses an HTTP response from a PatchConfigWithResponse call
func ParsePatchConfigResponse(rsp *http.Response) (*PatchConfigResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PatchConfigResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest MeshConfig
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest ErrorModel
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON403 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Get NGINX Service Mesh configuration
	// (GET /config)
	GetConfig(ctx echo.Context) error
	// Update NGINX Service Mesh Configuration
	// (PATCH /config)
	PatchConfig(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// GetConfig converts echo context to params.
func (w *ServerInterfaceWrapper) GetConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.GetConfig(ctx)
	return err
}

// PatchConfig converts echo context to params.
func (w *ServerInterfaceWrapper) PatchConfig(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshalled arguments
	err = w.Handler.PatchConfig(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/config", wrapper.GetConfig)
	router.PATCH(baseURL+"/config", wrapper.PatchConfig)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xce3PbOJL/Kije/jFTJ8vyKxO76urKE2czrsQZlaPcXFWS24LIlog1CXABULFmVt/9",
	"qhskxAcoyZnM3WxV8pdF4tEvdP+60cxvUazyQkmQ1kRXv0UaTKGkAfrxI0/u4R8lGIu/YiUtSPqTF0Um",
	"Ym6Fksd/N0riM3jkeZGBG5lAdPXD88vTUZSDMXwJ0VUk5IpnImGxkguxLDVNv2Ig+TyDhEmegyl4DIaZ",
	"VJVZwqSybA7MgGWfU5CMl1YxIf8OMc5kwtRzo80oMnEKOcfd/6JhEV1F/3a85ezYvTXHL7VW+k4lkEWb",
	"zWYUJWBiLQpcL7pCfpmQRWlZwTXPwYIeMaVZKU1ZFEpb6FA/Zvdg9ZrxhQXNeJJoMEbIZXsUE8aUgAvF",
	"KcQP+H6hNLPrQpkx0v5XpeciSUB+oZjPmmJe1ItdsdKARjGhIHlpU6XFr19PWrMUmHbmwRZcoA6TEhjp",
	"yJSLhYgFSMsKLVYigyWY8UeJe99KC1ry7B3oFWja4wv5vmzyHXubWYJlU4WqyjJnK38EyzGXlYEWWsVg",
	"DCRsDjEvDTC1YFwyUTHKDHHKANcmhb+XDXV8Ge/Pm7yXjfWuWM4fgJlSA1urknENpHyQFteFhH0WNmU2",
	"Bfa6nIOWYMGw6+ltRebXktV7NL7GxtWRrb2A0iwXdFjILPym5Hiup7cv6AThj74K2qdLLYiZt69u3/43",
	"Q6MSMbA7MCkyNY5GUaFVAdoK59SqUxpeuSGRm7fvyCftX9+rJ5JLIR+PcjDpES/EePszGkV2XeAQY7WQ",
	"SxQyKp0LCXqqtB1k1A1h6H2eQMnz8/MzvyXa4dIpthjc6okbBNffjCI8HUKjVX/wkq627XL8yS+g5ujT",
	"kT4yqRuwXGRIZltzLaK7PFyzhKZB4s4Zq04H02BLLfFwrok5Z+Xjj/KjnKVgoB5oamnTqIXKMvUZXbWQ",
	"C6VzMrURxiE8Tu6MzjO4wmWO2C8ptyzlRQESkrF7smai94xbWjzGCPuPEiQGOzyf3wl0GOvvadg9xCrP",
	"QSaQMO5CnVXM4qG2imkwKlsBrUNxBY9P0wZJhCxRSPvHcjI5i90i9DdcVc80cKMkxSESl3s7ZrNUGHRt",
	"LAOe4H5ueKHQPwmetWj3k/Q6sFWY2v5J6FhNU62DJuK8Ts9CnHfsm4Ysc9AiriwDRzGLykBG54BxkngV",
	"CTK5WLtxhqRTRX5WlLpQxgWxhrhPTs/OL579EDprzh6JLmEhNwe508r2N35BrjVf42/v7fvspWXO5ZEG",
	"nqBN1gY9YkKyl3KZCZOOHL9u4hwMKcTFoyeZz3711WSOnDKCGnwkLKXN1sfzJBG4C8+mDYUueGZgdEgA",
	"gHpJVKMBmTALGeQEzhJuObMKSc+FbK5/0o0NymbFPjX9bLOi5qBiYLMJcHmbV9p6Am/XDY8vctIhUqAF",
	"GmgFKvCxC0xcJtVPy5f9QCfyoLmg/Cxf1r6eRrWj2Mn4bDwJRSzcNbxgM1AGVkxU/AD6SMNSGKvXLjCO",
	"Y5UfS5MfN6KmEQnEXO+1MqJkVLEYsjEMWkMQ4ieVJejt87mQXUTP6l3Ie5VyKB6inrTKWJFxCR8lqgJH",
	"kq3RM3euOtAjRpz4wk29C/oqFKYb5rfI0V2pRYAKErIscwq2GK8iNCi5RolshV+/6amTF2KfsW+BGI4v",
	"rbql9EvtwCzkLW0d6nAOBs+4kbh9hnmq1AObC5mY6mR6ci8HkEucYTZxxx9/VMn6nfh1QHY5fxR5mTNi",
	"GhJmxK/eMN0SHsDPVbLuGH6OKuMWYXt0Ff3Px4/Jv394eJ3fLV99+s+/hEQIciW0knkF3vv0NAZshbLP",
	"nhxONpZnCGeEbOr5wSPUaBSpAqRJxcK2Nd4a06NZmPc305dV5twj2r1g72+mzGqOWRzmN49rBOpNYVX+",
	"q1p9rlQGnPKsTPHkR55xGQu5vAObqiQsmmWm5jxjOJ7N6wkspxkUeisBoSxCxu+wyopnJdSBXK1Aa0p+",
	"mZKMswL0UT1nzo0wLvfhfiHK4Vwq35CxVqVM/qbVXOAZzoAb+7dYye0PK8j9bH+wDP+ar+3QY4SRmVim",
	"CIM1l4nK/R/MflatH6y1Y+95tXnw+X9s6WhZRGtmzyJym+1FJ3c2M1tX4Is1w+GAXleA+clGP5RWBaMS",
	"viXY8kYt38DKAcPAUSRkk6kly3DQjmSnikJk+AJM0zQSmJdLjDxygUqTyooYZfqZa8JRVM0YRbEWqGme",
	"ASU+kINetjVSTQhz80Yt/0pJR5gT5MElJV/KxIKXGRJGFYYWXdt3PdIKrfB0Qmmud+XQVdpXkzb1s+o6",
	"SAJFptboEttq3q7fyJzHZhWP46w0FvQ4UzHPri4nl5MB+h7X++x4ioO2hlxDktewfnsQuqknsAdYO48u",
	"jE8gijLLhvThMJBDR6bNeIiZSn0eRe7iyQ1qTJLCPm2iR8v7ZszqgVsRWl0ae6NyLuQA2sQBLKERwwbb",
	"Fkn111jp5V4wiDim1n7TNbXDcyfwdSQckF0A8IwCEC50LtpC6VtZ5XLRjVSgKGrqIBxEg56u5zBCSCkI",
	"kLf+/PfmXxir89mbd/0UJOavYT2jrUOGQUdoXVQJONXEU2Dvprf3L5mrDrMX103HBfFRcXrxDJ/ER8XZ",
	"83OUreFHp5Pz59Wf55PLZ22Ptp3UL8Hx2exNmLYX18dGLCVCEiRzNnuDMCRVpTbfpd+P2Z2QFfY4PU/H",
	"7I4/Vj8v6V/HnH84naRtbHnyYXJ0+em309HF5rv0+3+efjg/uvzk/sIX7u1J9fbDWfdREI3mgykFqufA",
	"REItFkgpaCrPruhoWC3iDsZsDeh7r5VIBkWLslQLFqOdLKgmbVxxiHzoZ6Uf0PxNU96uXCxLC+a7/Pum",
	"uIWpJN6B8h1xfzjxEpyQBP+Zh2QYSuQDCf/XODFcsp9nb6ZseT994esX/SOUKjOAAvBN7U5/LkB619xe",
	"EmWKUBJiu62CvAG5tClVQPph9KAa8dN2dFlZdPXs4uLsgihwvyd7i8jEf0VUyI9NuY3Tr1VIolVdVE+p",
	"SICclkVCJmoVphg5T6iyOQxpG9eDPW0uBGTJXjr//6oGfQ/5h6XdT8qzvyWVf5qk8mtkj/9CGdufJEH7",
	"o5KxMbtDcD7HxIbHKdV+FhpNoH0bWmVgzjcGmAlVrAKJ3VG1a+OJx+tPyPS+PF0JBXhVDOQtCE3VgqEz",
	"5vU93BzQAaByIUF/cFAcYP+FDoV8ziHja8/DkwSSEdOQqxX+oTTTUGQ8rgoktRNPEsoxcBT9QUMCVtMJ",
	"raqIRlVECkZWpa3ZdQ2PMdnsrGp2TJxlwlhyo4HbChmrHKkMblW/ZT/NZlPauH3d/fz581DRuJ72Shfx",
	"noUJwQQWvjzZt/B0i4QP3MK1M9kuLqfb6YbE1niqDFiqLPhNuvSd7aLvrbK38jWsVzzbQ9y2bJ9ymWRg",
	"6oBtnD/wcVMqO2zHbeIuJzuJO1hwXulfVXCTXbTdQyI0HoTdlOlqmLMcBx6I0PpFQ4xWMS6VTX03hwwQ",
	"Pudm61cKrayKVbatPdFSXSHvtNBZXOzhYfYidKIuJ+d7lr1BzLh/aYSWPfEkINEf4Pv6lkEsmLC+W40V",
	"3OUaAa+iNA62W8xbwfFakvUaDot22brYw9bBVlnL7cuMMmSTl5MfdhH3Ptmnyvc3YVVehpbFuCjiAdzQ",
	"AArVuKDXDdKrSrtUg668fjvsyi93LXrjoNHL5TDm8Tv4CyzUErW60Cz/3CvOGdk0Kw27lW5MlW9lroPS",
	"lawhYdxg4l6tE/sxXd9yvouF4WjkKR+MRqe7Ft7r7f36XiIJGCskoY4qlHMNe49g1752UrXblXqS/hSu",
	"dLKLkUFX6nkYcqXPdi07eKz9skPHOoh5iqw01+5mf6CCUxdaG1Z/Pb2tRH49vfUOlLyrwJRAlRaFe0A2",
	"4xtYuqc6KINatz8Bz2w61FTQtwTyHSlNQtXOwQeBRv/sIC2XF4fRgru8O5ygd7+Domd7C2Heq3YcSfj4",
	"B45f25CHPOo23ERBpNYB1YNQOIxBAwCrDVX6CGMoOLcPUDtKbk/BNswFjW1Y68GMqHF3+LsakwOpfzsb",
	"otRq71VmI0GjezguTcF1sBfllxTIXSpNR/vAfA1jgS6ldH2wrLEDwZwxm3WesBy4bOSEoQUL7r6RsHQ1",
	"6CKxTbUql2l9ZBpRiYprqrR0jNY4j8s102W2PWDVIoe0p3TOlBNzW3QhxXfLCF+j/u9rGH3t+27GvS2j",
	"nU7KzSgyJAB9jxsNxADQMUjLl86da/rkxof+7ccMXCZ1ST/xovYV/zmPH0ASul5UlbBokSm6gfTl/pNg",
	"qV+W+bxycB1JbzZVna5H+HsDO1rTqxsHknBozIgqD/6RBqNK7dlGnCNiUXCqqDokT5Ooq6/+5IitVamb",
	"JbHtKv6Dij1Hak1d51V39C/X929v3766YrNhtqiqxuZgOdOQATfAjOW2NK7304Vp3egXR8MqDbHhyu7U",
	"Uem78JQcM08AQQwSvPGNwQlzDe4amCmr2xDF4pTLJSD2RSaRMFipbAVmzN4qtiy55tICmROaxWeuXX9l",
	"wa2Yi0xYyn1ynlRdkVZYqguGuY5G0Qq0cXpfnfCsSPmJq9OBpJ7F6Gw8oQ7VgtuUDslx7A/mEgLu754+",
	"AjB1933/zqfuXfU1zDDo9aXA2yS6il6BrQ7eqP3h3Olk8rTPegJ3PP5upmrT9N+t7PzKpPNRifsOxN3o",
	"nZ+fBZs4Xcdl4KLH9UO2WhzbrYXBW5nORUd9O9BoBWjcyFcX8PX9uLvAru+bG9fI0UnaaTtrN4WFbhR8",
	"xb9TsG9U1wNF9FYXksmPciWFVVrI5dis4roi7VuNfKDe1i9dMbJdenR1xKGqoaviBWt2roYWqpi5Cla/",
	"XuUKQq3yjyvm9Eo3rhgyUPpwxYhW6cEVEnzZwKX/22TfZe4DebrLidsZsEtng8mryyn7GaRL0VoJmUuv",
	"WsmUS418IuSSj1Cq4VKBQeCPuLwLrCjChxrHoqjftFW14D+5//3qZHxBDs513EeBDvmBbq8n7yiksDu2",
	"w9e9G5cWPqm/mXCNCpGykB1VX14qHThCkfdHZyc/bHqIZTKenHSbylrdYAd/ntj4BCDweeK7klzuosyy",
	"NdNo07CC5LDrGRcz6EvO88nJEB0+Ihy3PvekSWf7J20/Ct6MogsXUHbPCH1YSwIu85yj5jBg7eUuGkWP",
	"R4uLI3gsQAt0+3ggrS7R6gtu4zSAzuoWiadIrxtNm50cDqaDsRiNnhJKPzR6LMLhqXHfXd39+Ruzzaem",
	"bSkJPy9oxZ1JWIPqzejAT73akzqfen0KWOsNLISEXj9KXn0U+BS5E+6r16guGg3mb9wwzjAzy4ARgcxR",
	"6CES9SwRkQiXAkMokd3mV5XNfENGAdP7Boy+AaNvwOgbMPqTAyMXJ74EFh2AVxr/vcz/FZJqoSGHWkJ8",
	"vTgYEA29wY0IhhlCEJ3PfP1/tkGXVNEoKjX65WNeCIN22LDKbQHk0+Z/AwAA//+808KOrUcAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %s", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %s", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	var res = make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	var resolvePath = PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		var pathToFile = url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
