---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: meshconfigclasses.nsm.nginx.com
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  group: nsm.nginx.com
  names:
    kind: MeshConfigClass
    listKind: MeshConfigClassList
    plural: meshconfigclasses
    singular: meshconfigclass
  scope: Cluster
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: MeshConfigClass defines a class of MeshConfigs to the user for creating MeshConfig resources.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired state of MeshConfigClass.
            properties:
              controllerName:
                description: ControllerName is the name of the controller that is managing MeshConfigs
                  of this class.
                minLength: 1
                type: string  
            required:
            - controllerName
            type: object
          status:
            description: Status defines the current state of MeshConfigClass.
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
