---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: meshconfigs.nsm.nginx.com
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  group: nsm.nginx.com
  names:
    kind: MeshConfig
    listKind: MeshConfigList
    plural: meshconfigs
    singular: meshconfig
  scope: Namespaced
  versions:
  - name: v1alpha2
    schema:
      openAPIV3Schema:
        description: MeshConfig defines the top level CustomResource for holding the
          global static mesh configuration. This configuration is set on installation of the mesh
          and becomes immutable. To update the runtime configuration, see the MeshDynamicConfig CustomResource.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: Spec defines the desired installation configuration for NGINX Service Mesh.
            properties:
              meshConfigClassName:
                description: MeshConfigClassName used for this MeshConfig. This is
                  the name of a MeshConfigClass resource.
                minLength: 1
                type: string
              accessControlMode:
                description: AccessControlMode for service-to-service communication.
                enum:
                - allow
                - deny
                type: string
              clientMaxBodySize:
                description: ClientMaxBodySize is NGINX client max body size.
                pattern: ^\d+[kKmMgG]?$
                type: string
              disableAutoInjection:
                description: DisableAutoInjection disables automatic sidecar injection globally.
                type: boolean
              enableUDP:
                description: EnableUDP traffic proxying (beta).
                type: boolean
              enabledNamespaces:
                description: EnabledNamespaces is the list of namespaces where automatic
                  sidecar injection is enabled.
                items:
                  type: string
                type: array
              environment:
                description: Environment to deploy the mesh into.
                enum:
                - kubernetes
                - openshift
                type: string
              mtls:
                description: Mtls is the configuration for mutual TLS.
                properties:
                  caKeyType:
                    description: CaKeyType is the key type used for the SPIRE Server
                      CA.
                    enum:
                    - ec-p256
                    - ec-p384
                    - rsa-2048
                    - rsa-4096
                    type: string
                  caTTL:
                    description: CaTTL is the CA/signing key TTL in hours(h). Min
                      value 24h. Max value 999999h.
                    pattern: ^1[0-9]{2,5}(h)|2[4-9](h)|2[0-9][0-9]{1,5}(h)|[3-9][0-9]{1,5}(h)$
                    type: string
                  mode:
                    description: Mode for pod-to-pod communication.
                    enum:
                    - "off"
                    - permissive
                    - strict
                    type: string
                  svidTTL:
                    description: SvidTTL is the TTL of certificates issued to workloads
                      in hours(h) or minutes(m). Max value is 999999.
                    pattern: ^[1-9][0-9]{0,5}(h|m)$
                    type: string
                  trustDomain:
                    description: TrustDomain of the mesh.
                    type: string
                required:
                - caKeyType
                - caTTL
                - mode
                - svidTTL
                - trustDomain
                type: object
              namespace:
                description: Namespace that the NGINX Service Mesh control plane belongs to.
                type: string
              nginxErrorLogLevel:
                description: NGINXErrorLogLevel is the NGINX error log level.
                enum:
                - debug
                - info
                - notice
                - warn
                - error
                - crit
                - alert
                - emerg
                type: string
              nginxLBMethod:
                description: NGINXLBMethod is the NGINX load balancing method.
                enum:
                - least_conn
                - least_time
                - least_time last_byte
                - least_time last_byte inflight
                - random
                - random two
                - random two least_conn
                - random two least_time
                - random two least_time=last_byte
                - round_robin
                type: string
              nginxLogFormat:
                description: NGINXLogFormat is the NGINX log format.
                enum:
                - default
                - json
                type: string
              prometheusAddress:
                description: PrometheusAddress is the address of a Prometheus server
                  deployed in your Kubernetes cluster.
                type: string
              registry:
                description: Registry contains the NGINX Service Mesh image registry settings.
                properties:
                  disablePublicImages:
                    description: DisablePublicImages disables the pulling of third
                      party images from public repositories.
                    type: boolean
                  imagePullPolicy:
                    description: ImagePullPolicy for NGINX Service Mesh images.
                    enum:
                    - Never
                    - IfNotPresent
                    - Always
                    type: string
                  imageTag:
                    description: ImageTag used for pulling images from registry.
                    type: string
                  registryKeyName:
                    description: RegistryKeyName is the name of the registry key for pulling images.
                    type: string
                  server:
                    description: Server is the hostname:port for registry and path to images.
                    type: string
                  sidecarImage:
                    description: SidecarImage is the image to be used for the sidecar.
                    type: string
                  sidecarInitImage:
                    description: SidecarInitImage is the image to be used for the sidecar init container.
                    type: string
                required:
                - disablePublicImages
                - imagePullPolicy
                - imageTag
                - server
                - sidecarImage
                - sidecarInitImage
                type: object
              telemetry:
                description: Telemetry is the configuration for telemetry.
                properties:
                  exporters:
                    description: Exporters is the exporters configuration for telemetry.
                    properties:
                      otlp:
                        description: Otlp is the configuration for an OTLP gRPC exporter.
                        properties:
                          host:
                            description: Host of the OpenTelemetry gRPC exporter to connect to.
                            minLength: 1
                            type: string
                          port:
                            description: Port of the OpenTelemetry gRPC exporter to connect to.
                            format: int32
                            maximum: 65535
                            minimum: 0
                            type: integer
                        required:
                        - host
                        - port
                        type: object
                    required:
                    - otlp
                    type: object
                  samplerRatio:
                    description: SamplerRatio is the percentage of traces that are
                      processed and exported to the telemetry backend.
                    maximum: 1
                    minimum: 0
                    type: number
                    format: float
                required:
                - exporters
                - samplerRatio
                type: object
              transparent:
                description: Transparent is set when the mesh is removed to turn all
                  sidecar proxies transparent.
                type: boolean
            required:
            - meshConfigClassName
            - accessControlMode
            - clientMaxBodySize
            - disableAutoInjection
            - enableUDP
            - enabledNamespaces
            - environment
            - mtls
            - namespace
            - nginxErrorLogLevel
            - nginxLBMethod
            - nginxLogFormat
            - registry
            - transparent
            type: object
          status:
            description: Status defines the configuration status for NGINX Service Mesh.
            properties:
              transparent:
                description: Transparent status is updated once the mesh controller
                  has successfully turned all sidecar proxies transparent.
                type: boolean
            required:
            - transparent
            type: object
        required:
        - spec
        type: object
    served: true
    storage: true
    subresources:
      status: {}
