---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: tcproutes.specs.smi-spec.io
  labels:
    app.kubernetes.io/part-of: nginx-service-mesh
spec:
  group: specs.smi-spec.io
  scope: Namespaced
  names:
    kind: TCPRoute
    shortNames:
    - tr
    plural: tcproutes
    singular: tcproute
  versions:
  - name: v1alpha3
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
