[build]
  base = "docs/"
  publish = "public"
  command = "./scripts/copy-docs.sh && hugo --gc"
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- ./"

[build.environment]
  HUGO_VERSION = "0.80.0"

[context.docs-development]
  command = "./scripts/copy-docs.sh && hugo --gc -e development"

[context.docs-staging]
  command = "./scripts/copy-docs.sh && hugo --gc -e staging"

[context.docs-preview]
  command = "./scripts/copy-docs.sh && hugo --gc -e preview"

[context.branch-deploy]
  command = "./scripts/copy-docs.sh && hugo --gc -d public/nginx-service-mesh -b $DEPLOY_PRIME_URL/nginx-service-mesh"

[context.deploy-preview]
  command = "./scripts/copy-docs.sh && hugo --gc -d public/nginx-service-mesh -b $DEPLOY_PRIME_URL/nginx-service-mesh"

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "https://docs.nginx.com"

[[redirects]]
  from = "/"
  to = "/nginx-service-mesh/"
  status = 301
  force = true

[[redirects]]
  from = "https://mesh-public-docs.netlify.app/robots.txt"
  to = "https://docs.nginx.com/robots.txt"
  status = 301
  force = true

[[redirects]]
  from = "*"
  to = "/nginx-service-mesh/404.html"
  status = 404
