name: Documentation

on:
  push:
  pull_request:

concurrency:
  group: ${{ github.ref_name }}-docs
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  markdown-lint:
    name: Markdown Lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Lint
        uses: avto-dev/markdown-lint@04d43ee9191307b50935a753da3b775ab695eceb # v1.5.0
        with:
          config: docs/mdlint_conf.json
          args: docs/content/**/*.md
  markdown-link-check:
    name: Markdown Link Check
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Link Check
        uses: gaurav-nelson/github-action-markdown-link-check@d53a906aa6b22b8979d33bc86170567e619495ec # v1.0.15
        with:
          config-file: docs/md-linkcheck-config.json
          folder-path: docs/content
