name: Mend

on:
  push:
    branches:
      - main
      - release-*
    paths-ignore:
      - docs/**
      - examples/**
  workflow_dispatch:

concurrency:
  group: ${{ github.ref_name }}-mend
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  scan:
    name: Mend
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@8f4b7f84864484a7bf31766abe9204da3cbe65b3 # v3.5.0
      - name: Scan
        uses: TheAxZim/Whitesource-Scan-Action@ae848d3fc813c97f7e466da97ccd2b12b4bad9b8
        with:
          wssURL: ${{ secrets.WSS_URL }}
          apiKey:  ${{ secrets.WSS_NGINX_TOKEN }}
          productName: service-mesh_${{ github.ref_name }}
          projectName: nginx-service-mesh
